apiVersion: v1
kind: Pod
metadata:
  name: pod-mt
  labels:
    app: main-mt
spec:
  containers:
  - name: network-multitool
    image: wbitt/network-multitool
    env:
      - name: HTTP_PORT
        value: "8080"