apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-ng
spec:
  ports:
  - name: nginx-svc
    port: 80
  selector:
    app: main-ng

# apiVersion: v1
# kind: Service
# metadata:
#   name: service
# spec:
#   ports:
#     - name: web
#       port: 80